baseline: A personal blog
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: A ready to use static blog, powered by Cecil.
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Bit by Bit
baseurl: /
canonicalurl: true
